// src/services/schedules.ts
import api from "./api";
import type { Appointment } from "../types/appointment";
import type { DoctorScheduleItem } from "../hooks/useDoctorSchedule";

export type CreateDoctorSchedulePayload = {
  doctorId: number;
  day: string;
  slots: string[];
};

export type AutoGenerateSchedulePayload = {
  doctorId: number;
  date: string;
  startTime: string;
  endTime: string;
  slotDuration: number;
};

type ScheduleApiItem = {
  id?: number;
  doctor_id?: number;
  doctorId?: number;
  date?: string;
  day?: string;
  start_time?: string;
  end_time?: string;
  is_available?: boolean;
  is_booked?: boolean;
};

type ScheduleApiResponse =
  | ScheduleApiItem[]
  | {
      success?: boolean;
      count?: number;
      items?: ScheduleApiItem[];
      data?: ScheduleApiItem[];
    };

type AppointmentApiItem = Appointment & {
  patient?: {
    id?: number;
    name?: string;
    phone?: string;
  };
  availability?: {
    id?: number;
    date?: string;
    start_time?: string;
    end_time?: string;
  };
};

type AppointmentsApiResponse =
  | AppointmentApiItem[]
  | {
      success?: boolean;
      count?: number;
      items?: AppointmentApiItem[];
      data?: AppointmentApiItem[];
    };

function normalizeScheduleItem(item: ScheduleApiItem): DoctorScheduleItem {
  return {
    id: item.id ?? Math.floor(Math.random() * 1_000_000),
    doctor_id: item.doctor_id ?? item.doctorId ?? 0,
    date: item.date ?? item.day ?? "",
    start_time: item.start_time ?? "",
    end_time: item.end_time ?? "",
    is_available: item.is_available ?? true,
    is_booked: item.is_booked ?? false,
  };
}

function normalizeAppointment(item: AppointmentApiItem): Appointment {
  return {
    ...item,
    patient_name:
      item.patient_name ??
      item.patient?.name ??
      "بیمار نامشخص",
    date:
      item.date ??
      item.availability?.date ??
      "",
    start_time:
      item.start_time ??
      item.availability?.start_time ??
      "",
    end_time:
      item.end_time ??
      item.availability?.end_time ??
      "",
  };
}

export async function getDoctorSchedule(
  doctorId: number
): Promise<DoctorScheduleItem[]> {
  const response = await api.get<ScheduleApiResponse>("/availability", {
    params: { doctor_id: doctorId },
  });

  const data = response.data;

  if (Array.isArray(data)) {
    return data.map(normalizeScheduleItem);
  }

  if (data?.items && Array.isArray(data.items)) {
    return data.items.map(normalizeScheduleItem);
  }

  if (data?.data && Array.isArray(data.data)) {
    return data.data.map(normalizeScheduleItem);
  }

  return [];
}

export async function createDoctorSchedule(
  payload: CreateDoctorSchedulePayload
) {
  const body = {
    doctor_id: payload.doctorId,
    date: payload.day,
    slots: payload.slots,
  };

  const response = await api.post("/availability", body);
  return response.data;
}

export async function autoGenerateDoctorSchedule(
  payload: AutoGenerateSchedulePayload
) {
  const body = {
    doctor_id: payload.doctorId,
    date: payload.date,
    start_time: payload.startTime,
    end_time: payload.endTime,
    slot_duration: payload.slotDuration,
  };

  const response = await api.post("/availability/auto-generate", body);
  return response.data;
}

export async function clearDoctorSchedule(doctorId: number) {
  const response = await api.delete(
    `/availability/clear/doctor/${doctorId}`
  );
  return response.data;
}

export async function getAppointmentsByDoctor(
  doctorId: number
): Promise<Appointment[]> {
  const response = await api.get<AppointmentsApiResponse>("/appointments");
  const data = response.data;

  let items: AppointmentApiItem[] = [];

  if (Array.isArray(data)) {
    items = data;
  } else if (data?.items && Array.isArray(data.items)) {
    items = data.items;
  } else if (data?.data && Array.isArray(data.data)) {
    items = data.data;
  }

  return items
    .filter((item) => item.doctor_id === doctorId)
    .map(normalizeAppointment)
    .sort((a, b) => {
      const aDate = `${a.date ?? ""} ${a.start_time ?? ""}`;
      const bDate = `${b.date ?? ""} ${b.start_time ?? ""}`;
      return bDate.localeCompare(aDate);
    });
}