import { useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import {
  CalendarDays,
  Clock3,
  RefreshCw,
  Trash2,
  PlusCircle,
  CalendarClock,
  CheckCircle2,
} from "lucide-react";
import { Link } from "react-router-dom";

import { getMyProfile } from "../../services/profile";
import {
  autoGenerateDoctorSchedule,
  clearDoctorSchedule,
  getDoctorSchedule,
} from "../../services/schedules";
import type { DoctorScheduleItem } from "../../hooks/useDoctorSchedule";

function toPersianDigits(value: string | number) {
  return String(value).replace(/\d/g, (d) => "۰۱۲۳۴۵۶۷۸۹"[Number(d)]);
}

function formatDate(date?: string | null) {
  if (!date) return "تاریخ نامشخص";

  try {
    const [year, month, day] = date.split("-").map(Number);
    return new Intl.DateTimeFormat("fa-IR", {
      year: "numeric",
      month: "long",
      day: "numeric",
      weekday: "long",
    }).format(new Date(year, month - 1, day));
  } catch {
    return date;
  }
}

function todayString() {
  const d = new Date();
  const y = d.getFullYear();
  const m = `${d.getMonth() + 1}`.padStart(2, "0");
  const day = `${d.getDate()}`.padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export default function DoctorSchedule() {
  const [date, setDate] = useState(todayString());
  const [startTime, setStartTime] = useState("09:00");
  const [endTime, setEndTime] = useState("12:00");
  const [slotDuration, setSlotDuration] = useState(30);

  const {
    data: profile,
    isLoading: profileLoading,
    isError: profileError,
    refetch: refetchProfile,
  } = useQuery({
    queryKey: ["doctor-profile"],
    queryFn: getMyProfile,
  });

  const doctorId = profile?.id;

  const {
    data: schedule = [],
    isLoading,
    isError,
    refetch,
    isFetching,
  } = useQuery<DoctorScheduleItem[]>({
    queryKey: ["doctor-schedule", doctorId],
    queryFn: () => getDoctorSchedule(doctorId as number),
    enabled: Boolean(doctorId),
  });

  const autoGenerateMutation = useMutation({
    mutationFn: async () => {
      if (!doctorId) throw new Error("doctorId not found");

      return autoGenerateDoctorSchedule({
        doctorId,
        date,
        startTime: startTime.length === 5 ? `${startTime}:00` : startTime,
        endTime: endTime.length === 5 ? `${endTime}:00` : endTime,
        slotDuration,
      });
    },
    onSuccess: () => {
      refetch();
    },
  });

  const clearMutation = useMutation({
    mutationFn: async () => {
      if (!doctorId) throw new Error("doctorId not found");
      return clearDoctorSchedule(doctorId);
    },
    onSuccess: () => {
      refetch();
    },
  });

  const freeSlots = useMemo(
    () => schedule.filter((item) => !item.is_booked && item.is_available),
    [schedule]
  );

  const bookedSlots = useMemo(
    () => schedule.filter((item) => item.is_booked),
    [schedule]
  );

  const groupedSchedule = useMemo(() => {
    const map = new Map<string, DoctorScheduleItem[]>();

    for (const item of schedule) {
      const key = item.date || "بدون تاریخ";
      if (!map.has(key)) map.set(key, []);
      map.get(key)!.push(item);
    }

    return Array.from(map.entries()).sort((a, b) => a[0].localeCompare(b[0]));
  }, [schedule]);

  if (profileLoading) {
    return (
      <div dir="rtl" className="p-10 text-center font-black">
        در حال دریافت اطلاعات پزشک...
      </div>
    );
  }

  if (profileError || !doctorId) {
    return (
      <div dir="rtl" className="p-10">
        <div className="mx-auto max-w-3xl rounded-3xl border border-red-200 bg-red-50 p-6 text-center">
          <div className="text-lg font-black text-red-700">
            دریافت اطلاعات پزشک انجام نشد
          </div>

          <button
            onClick={() => refetchProfile()}
            className="mt-4 rounded-2xl bg-red-600 px-5 py-2.5 text-sm font-black text-white"
          >
            تلاش مجدد
          </button>
        </div>
      </div>
    );
  }

  return (
    <div dir="rtl" className="min-h-screen bg-slate-50 p-5">
      <div className="mx-auto max-w-7xl">
        <div className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-3xl bg-gradient-to-br from-slate-950 via-cyan-950 to-slate-900 p-6 text-white shadow-sm">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-4 py-2 text-xs font-black text-cyan-100 backdrop-blur">
              Doctor Schedule
            </div>

            <h1 className="mt-4 text-3xl font-black">مدیریت زمان‌های پزشک</h1>

            <p className="mt-3 text-sm leading-7 text-slate-300">
              {profile.name} — بازه‌های زمانی پزشک را بساز، مرور کن و در صورت
              نیاز پاک کن.
            </p>
          </div>

          <div className="flex flex-wrap gap-3">
            <button
              onClick={() => refetch()}
              className="flex items-center gap-2 rounded-2xl bg-white/10 px-4 py-2.5 text-sm font-black text-white backdrop-blur"
            >
              <RefreshCw
                size={16}
                className={isFetching ? "animate-spin" : ""}
              />
              بروزرسانی
            </button>

            <Link
              to="/doctor-dashboard"
              className="rounded-2xl bg-white px-4 py-2.5 text-sm font-black text-slate-900"
            >
              داشبورد
            </Link>

            <Link
              to="/doctor-appointments"
              className="rounded-2xl bg-cyan-600 px-4 py-2.5 text-sm font-black text-white"
            >
              مشاهده نوبت‌ها
            </Link>
          </div>
        </div>

        <div className="grid gap-5 md:grid-cols-3">
          <div className="rounded-3xl bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <div>
                <div className="text-sm font-bold text-slate-500">
                  کل بازه‌ها
                </div>
                <div className="mt-2 text-3xl font-black text-slate-900">
                  {toPersianDigits(schedule.length)}
                </div>
              </div>
              <div className="rounded-2xl bg-cyan-100 p-3 text-cyan-700">
                <CalendarDays size={22} />
              </div>
            </div>
          </div>

          <div className="rounded-3xl bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <div>
                <div className="text-sm font-bold text-slate-500">
                  بازه‌های آزاد
                </div>
                <div className="mt-2 text-3xl font-black text-slate-900">
                  {toPersianDigits(freeSlots.length)}
                </div>
              </div>
              <div className="rounded-2xl bg-emerald-100 p-3 text-emerald-700">
                <CheckCircle2 size={22} />
              </div>
            </div>
          </div>

          <div className="rounded-3xl bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <div>
                <div className="text-sm font-bold text-slate-500">
                  بازه‌های رزرو شده
                </div>
                <div className="mt-2 text-3xl font-black text-slate-900">
                  {toPersianDigits(bookedSlots.length)}
                </div>
              </div>
              <div className="rounded-2xl bg-amber-100 p-3 text-amber-700">
                <CalendarClock size={22} />
              </div>
            </div>
          </div>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-[380px_1fr]">
          <div className="rounded-3xl bg-white p-6 shadow-sm">
            <div className="mb-5">
              <h2 className="text-xl font-black text-slate-900">
                ساخت بازه زمانی
              </h2>
              <p className="mt-2 text-sm text-slate-500">
                با استفاده از auto-generate برای پزشک بازه زمانی بساز
              </p>
            </div>

            <div className="space-y-4">
              <div>
                <label className="mb-2 block text-sm font-bold text-slate-700">
                  تاریخ
                </label>
                <input
                  type="date"
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                  className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:border-cyan-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="mb-2 block text-sm font-bold text-slate-700">
                    شروع
                  </label>
                  <input
                    type="time"
                    value={startTime}
                    onChange={(e) => setStartTime(e.target.value)}
                    className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:border-cyan-500"
                  />
                </div>

                <div>
                  <label className="mb-2 block text-sm font-bold text-slate-700">
                    پایان
                  </label>
                  <input
                    type="time"
                    value={endTime}
                    onChange={(e) => setEndTime(e.target.value)}
                    className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:border-cyan-500"
                  />
                </div>
              </div>

              <div>
                <label className="mb-2 block text-sm font-bold text-slate-700">
                  مدت هر نوبت (دقیقه)
                </label>
                <select
                  value={slotDuration}
                  onChange={(e) => setSlotDuration(Number(e.target.value))}
                  className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:border-cyan-500"
                >
                  <option value={15}>۱۵ دقیقه</option>
                  <option value={20}>۲۰ دقیقه</option>
                  <option value={30}>۳۰ دقیقه</option>
                  <option value={45}>۴۵ دقیقه</option>
                  <option value={60}>۶۰ دقیقه</option>
                </select>
              </div>

              <button
                onClick={() => autoGenerateMutation.mutate()}
                disabled={autoGenerateMutation.isPending}
                className="flex w-full items-center justify-center gap-2 rounded-2xl bg-cyan-600 px-4 py-3 text-sm font-black text-white disabled:opacity-60"
              >
                <PlusCircle size={18} />
                {autoGenerateMutation.isPending
                  ? "در حال ساخت..."
                  : "ایجاد بازه‌های زمانی"}
              </button>

              <button
                onClick={() => {
                  if (
                    window.confirm(
                      "همه بازه‌های زمانی این پزشک حذف شوند؟"
                    )
                  ) {
                    clearMutation.mutate();
                  }
                }}
                disabled={clearMutation.isPending}
                className="flex w-full items-center justify-center gap-2 rounded-2xl bg-red-600 px-4 py-3 text-sm font-black text-white disabled:opacity-60"
              >
                <Trash2 size={18} />
                {clearMutation.isPending
                  ? "در حال حذف..."
                  : "حذف همه بازه‌های این پزشک"}
              </button>
            </div>

            {(autoGenerateMutation.isError || clearMutation.isError) && (
              <div className="mt-4 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">
                عملیات انجام نشد. داده‌های ورودی یا دسترسی را بررسی کن.
              </div>
            )}

            {autoGenerateMutation.isSuccess && (
              <div className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">
                بازه‌های زمانی با موفقیت ساخته شدند.
              </div>
            )}

            {clearMutation.isSuccess && (
              <div className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">
                همه بازه‌های این پزشک حذف شدند.
              </div>
            )}
          </div>

          <div className="rounded-3xl bg-white p-6 shadow-sm">
            <div className="mb-5 flex items-center justify-between gap-4">
              <div>
                <h2 className="text-xl font-black text-slate-900">
                  لیست زمان‌های پزشک
                </h2>
                <p className="mt-2 text-sm text-slate-500">
                  بازه‌های زمانی ثبت‌شده بر اساس تاریخ
                </p>
              </div>
            </div>

            {isLoading ? (
              <div className="py-10 text-center font-black text-slate-600">
                در حال دریافت برنامه زمانی...
              </div>
            ) : isError ? (
              <div className="rounded-2xl bg-red-50 p-5 text-center font-black text-red-700">
                خطا در دریافت برنامه زمانی پزشک
              </div>
            ) : groupedSchedule.length === 0 ? (
              <div className="rounded-2xl bg-slate-50 p-8 text-center font-black text-slate-600">
                هنوز هیچ بازه زمانی ثبت نشده است
              </div>
            ) : (
              <div className="space-y-6">
                {groupedSchedule.map(([groupDate, slots]) => (
                  <div
                    key={groupDate}
                    className="rounded-3xl border border-slate-200 p-5"
                  >
                    <div className="mb-4 flex items-center justify-between gap-3">
                      <div>
                        <div className="text-lg font-black text-slate-900">
                          {formatDate(groupDate)}
                        </div>
                        <div className="mt-1 text-sm text-slate-500">
                          {toPersianDigits(slots.length)} بازه
                        </div>
                      </div>
                    </div>

                    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
                      {slots.map((slot) => (
                        <div
                          key={slot.id}
                          className="rounded-2xl bg-slate-50 p-4"
                        >
                          <div className="flex items-center gap-2 font-black text-slate-900">
                            <Clock3 size={16} />
                            {toPersianDigits(slot.start_time)}
                            {" تا "}
                            {toPersianDigits(slot.end_time)}
                          </div>

                          <div className="mt-3">
                            {slot.is_booked ? (
                              <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-700">
                                رزرو شده
                              </span>
                            ) : (
                              <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">
                                آزاد
                              </span>
                            )}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}